In [2]:
import statistics as st

In [13]:
a= [10, 20, 50, 10, 21, 90]

In [5]:
mn = st.mean(a)
print("mean : ", mn)

mean :  33.5


In [11]:
md = st.mode(a)
print("mode :", md)

mode : 10


In [14]:
mdn = st.median(a)
print("median :", mdn)

median : 35.5


In [15]:
import numpy as np


In [16]:
b =  np.array([[10, 20, 30, 50, 10],[1, 2, 3, 5, 6]])

In [17]:
print(b)

[[10 20 30 50 10]
 [ 1  2  3  5  6]]


In [18]:
print(b.ndim)

2


In [19]:

b=np.array([[10, 20, 30, 50, 10],[1, 2, 3, 5, 6],[1,1,1,1,1]])
print(b)
print("Dim:",b.ndim)
print("Shape:",b.shape)


[[10 20 30 50 10]
 [ 1  2  3  5  6]
 [ 1  1  1  1  1]]
Dim: 2
Shape: (3, 5)


In [20]:
print("Size:",b.size)
print("Item Size:",b.itemsize)
print("Data type:",b.dtype)

Size: 15
Item Size: 8
Data type: int64


In [21]:
c=np.empty((5,5))

In [22]:
d=np.arange(0,100,2)
print(d)


[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [24]:
e=np.reshape(d,(10,5))
print(e)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]
 [60 62 64 66 68]
 [70 72 74 76 78]
 [80 82 84 86 88]
 [90 92 94 96 98]]


In [25]:
 f=np.reshape(e,(2,5,5))
 print(f)

[[[ 0  2  4  6  8]
  [10 12 14 16 18]
  [20 22 24 26 28]
  [30 32 34 36 38]
  [40 42 44 46 48]]

 [[50 52 54 56 58]
  [60 62 64 66 68]
  [70 72 74 76 78]
  [80 82 84 86 88]
  [90 92 94 96 98]]]


In [28]:
g = np.full((3,3),5)
print(g)


[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [27]:
print("Particular element:",d[10])

Particular element: 20


In [29]:
print("ELement upto 10:",d[:10])




ELement upto 10: [ 0  2  4  6  8 10 12 14 16 18]


In [31]:
print("Last 5 element:",d[-10:])


Last 5 element: [80 82 84 86 88 90 92 94 96 98]


In [32]:
print("Alternative Numbers:",d[::2])

Alternative Numbers: [ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92
 96]


In [33]:
import pandas as pd

In [39]:
p_dict = {'pid':[1,2,3,4,5], 'value': [10,20,30,40,50], 'vendor':['V1','V2','V3','V4','V5']}


In [40]:
print(p_dict)

{'pid': [1, 2, 3, 4, 5], 'value': [10, 20, 30, 40, 50], 'vendor': ['V1', 'V2', 'V3', 'V4', 'V5']}


In [43]:
df = pd.DataFrame(p_dict)
df

pid  value vendor
0    1     10     V1
1    2     20     V2
2    3     30     V3
3    4     40     V4
4    5     50     V5