In [1]:
import statistics as st
a = [10,12,30,45,60,75,90]

In [2]:
mn = st.mean(a)
print("mean: ",mn)

mean:  46


In [3]:
md = st.mode(a)
print("mode: ",md)

mode:  10


In [4]:
mdn = st.median(a)
print("median: ",mdn)

median:  45


In [5]:
import numpy as np
b = np.array([[10,20,30,50,10], [1,2,3,5,6]])
print(b)

[[10 20 30 50 10]
 [ 1  2  3  5  6]]


In [6]:
print(b.ndim)

2


In [7]:
b = np.array([[10,20,30,50,10], [1,2,3,5,6], [1,1,1,1,1]])
print(b)
print("Dim: ",b.ndim)
print("Shape: ",b.shape)
print("Size: ", b.size)
print("Item Size: ",b.itemsize) #integer size 4 or 8 acc. to complier
print("Data type: ",b.dtype)


[[10 20 30 50 10]
 [ 1  2  3  5  6]
 [ 1  1  1  1  1]]
Dim:  2
Shape:  (3, 5)
Size:  15
Item Size:  8
Data type:  int64


In [8]:
c = np.empty((5,5))
print(c)

[[9.31371898e-312 7.80623720e-322 0.00000000e+000 0.00000000e+000
  1.06811354e-306]
 [1.16096346e-028 9.82205649e+252 1.11789342e+253 1.49896763e-076
  8.45067653e-053]
 [1.81152935e-152 6.03969075e-154 1.05392793e+141 6.03823535e-154
  1.27727749e-153]
 [1.22179638e+199 7.91612123e+093 2.04632868e-115 7.91608575e+093
  1.78798477e-052]
 [2.67704487e+092 1.75353417e+136 1.11492077e+277 6.96742065e+252
  6.79769279e-310]]


In [9]:
g = np.full((3,3),5)
print(g)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [10]:
d = np.arange(0,100,2) #(start, end, step) - create array with fixed interval
print(d)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [11]:
e = np.reshape(d, (10,5)) #reshape 'd' to 10 row 5 col
print(e)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]
 [60 62 64 66 68]
 [70 72 74 76 78]
 [80 82 84 86 88]
 [90 92 94 96 98]]


In [12]:
f = np.reshape(e, (2,5,5)) #reshape 'e' to 2 block's of 5x5
print(f)
print(f.ndim) 

[[[ 0  2  4  6  8]
  [10 12 14 16 18]
  [20 22 24 26 28]
  [30 32 34 36 38]
  [40 42 44 46 48]]

 [[50 52 54 56 58]
  [60 62 64 66 68]
  [70 72 74 76 78]
  [80 82 84 86 88]
  [90 92 94 96 98]]]
3


In [13]:
print("Last 10 elements: ",d[-10:])

Last 10 elements:  [80 82 84 86 88 90 92 94 96 98]


In [14]:
print("Alternative Numbers: ",d[::2])

Alternative Numbers:  [ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92
 96]


In [15]:
import pandas as pd
p_dict = {'pid':[1,2,3,4,5], 'value':[10,20,30,40,50], 'vendor':['V1','V2','V3','V4','V5']}
print(p_dict)
df = pd.DataFrame(p_dict)
df

{'pid': [1, 2, 3, 4, 5], 'value': [10, 20, 30, 40, 50], 'vendor': ['V1', 'V2', 'V3', 'V4', 'V5']}


,pid,value,vendor
0,1,10,V1
1,2,20,V2
2,3,30,V3
3,4,40,V4
4,5,50,V5
